import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'CRUD app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#a8f0a7]'>
        <div>
          <ul className='flex gap-2 bg-[#32b9ec] p-5 font-semibold'>
            <li><Link className='bg-white p-3 rounded' href={"/"}>Home</Link></li>
            <li><Link className='bg-white p-3 rounded' href={"/products"}>Products</Link></li>
            <li><Link className='bg-white p-3 rounded' href={"/gallary"}>Gallary</Link></li>
            <li><Link className='bg-white p-3 rounded' href={"/aboutus"}>About us</Link></li>
          </ul>
        </div>
        <div className='min-h-[595px]'>{children}</div>
      </body>
    </html>
  )
}

